frc1418/VictiScout

README.md, index.html, package.json, renderData.js, script.js
@hashFactory @addict1 Take a look
=> Server compatibility

script.js
This fixes gear point value and autonomous accuracy calculations.
=> Fix parsing numbers incorrectly

index.html, style.css
It wasn't doing anything, since the images that used to be inside the divs no longer exist.
=> Remove extraneous tasks class

index.html, script.js
=> Dynamically generate +- buttons

index.html, main.js
Fixes #69 
I felt like a drop down would be better than two checkboxes (where at least one will not be used most of the time)
=> Add climbing assist selector

script.js
=> Add confirm box to replace or add data.

data.css, data.html, data.js
=> Data warning

index.html, script.js
Closes #77 
Closes #76 
For #76, we might want to specify the left/right. (Facing the middle?)
=> Save auto start position when submitting a form.

index.html, main.js, style.css
=> Various tweaks and fixes after VAGDC competition

index.html, script.js, style.css
Includes color and position selector, both positioned to the right of team and match number
=> Add position selector

index.html
=> Add note-taking instructions

data.css
=> Add strikethrough and cursor to added files for deletion

data.css, data.html, index.html, style.css, theme.css
=> Transfer shared styles to theme file

script.js
=> Remove climbed listener

index.html
=> Update level started and level ended

index.html
=> Add closing select tags

script.js
=> Create new JS element for parked

css/data.css, data.html, js/data.js
=> Vertically center data warning message

index.html, js/script.js
=> Fix and rename choose option

index.html
=> Add climb assist tick box

js/main.js, package.json
=> Final fixes for first Deep Space competition

index.html, js/script.js
=> Remove position and color from data collection

index.html, js/data.js, js/script.js
fix #159 fix #158 fix #153 fix #154 fix #151 fix #149 fix #147
=> Fix some first competition complaints

data.html, js/data.js
Fixes #161 
Fixes #155 
Fixes #106
=> Add fields in CSV file for rocket balls and rocket hatches

js/data.js
Closes #179 
Now someone can solve #180 and use the new functions.
=> Extract data processing and field creation

css/style.css, index.html, js/data.js
There's a bunch of commented out stuff at the bottom of css/style.css. Should I take that out also?
=> Deletes old code

js/script.js
=> Stop data from submitting without position

js/data.js, js/main.js
- reloads on delete
- initial size fits all data
=> Fix Data Page
